// types.js
export const MARK_ATTENDANCE = 'MARK_ATTENDANCE';
export const FETCH_ALL_ATTENDANCE_SUCCESS = 'FETCH_ALL_ATTENDANCE_SUCCESS';
export const FETCH_ALL_ATTENDANCE_FAILURE = 'FETCH_ALL_ATTENDANCE_FAILURE';
export const UPDATE_ATTENDANCE = 'UPDATE_ATTENDANCE';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const FETCH_NOTIFICATIONS = 'FETCH_NOTIFICATIONS';
export const DELETE_ATTENDANCE = 'DELETE_ATTENDANCE';
