export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const MARK_ATTENDANCE = "MARK_ATTENDANCE";
export const FETCH_ALL_ATTENDANCE = "FETCH_ALL_ATTENDANCE";
export const FETCH_NOTIFICATIONS = "FETCH_NOTIFICATIONS";
